### ISSUE TITLE
Move all unit tests from /src/main to /src/test

### ISSUE THREAD

**Issue by jhalterman** [Netflix/Turbine#21]
I noticed that unit tests are being bundled in the main distro. Ideally these, along with any testing related dependencies, should be moved to a separate source tree such as /src/test.

**Comment by UnquietCode** [comment]
I'm guessing the answer from [Hystrix/147](https://github.com/Netflix/Hystrix/issues/147) applies here as well.

**Comment by benjchristensen** [comment]
As of Hystrix 1.4 they have all been moved. Turbine 2 also moves them out. We are not going to do any further major work on Turbine 1.
