### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by joelittlejohn** [Netflix/Turbine#34]
Hi guys, any chance of a 0.5 release being cut? It's been a while (~15 months) since 0.4 was released and there's been quite a few changes in that time (including the introduction of turbine-contrib).

**Comment by joelittlejohn** [comment]
Are you able to publish a 0.5 SNAPSHOT anywhere? ~~(preferably after merging #35 :smile:)~~

**Comment by joelittlejohn** [comment]
Hi @benjchristensen, I see you're kicking off 2.x development and getting the house in order. Do you think you'd be able to cut a final 0.5 release from the current 1.x branch?

**Comment by benjchristensen** [comment]
Yes, I can do that. Will do it now.

**Comment by benjchristensen** [comment]
Turbine 0.5 has been released.

**Comment by joelittlejohn** [comment]
Thanks man!
