### ISSUE TITLE
gradlew build failed

### ISSUE THREAD

**Issue by serzh** [Netflix/Turbine#47]
While bootstrapping project, I have encountered following error:

```
Downloading http://services.gradle.org/distributions/gradle-1.5-bin.zip
Unzipping /root/.gradle/wrapper/dists/gradle-1.5-bin/9si5v6u7tk37kj5dlsrdcm595/gradle-1.5-bin.zip to /root/.gradle/wrapper/dists/gradle-1.5-bin/9si5v6u7tk37kj5dlsrdcm595
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-1.5-bin/9si5v6u7tk37kj5dlsrdcm595/gradle-1.5/bin/gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/Turbine/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating root project 'turbine'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 43.994 secs
```

**Comment by benjchristensen** [comment]
yes something is broken with the build config. It seems this might be the issue: "Set executable permissions for"

**Comment by serzh** [comment]
Following the output, the problem might be

```
* What went wrong:
A problem occurred evaluating root project 'turbine'.
> Could not find method jcenter() for arguments [] on repository container.
```

**Comment by pvenkatakrishnan** [comment]
Update: I was able to get Turbine to build successfully. Did a fresh clone and build again and things worked.
Previously, i noticed `mavenCentral() // maven { url 'http://jcenter.bintray.com' }` from `build.gradle` did not complete fine. And hence the next line `jcenter()` failed.
Unsure why the second time it worked.

~~I am seeing the same issue~~

```
* What went wrong:
A problem occurred evaluating root project 'turbine'.
> Could not find method jcenter() for arguments [] on repository container. 
```

~~Any tips on how to get it to build ?~~

**Comment by benjchristensen** [comment]
I think it is fixed here: https://github.com/Netflix/Turbine/pull/52

**Comment by benjchristensen** [comment]
I am wrestling build issues to try and get artifacts out on Maven Central.

**Comment by pvenkatakrishnan** [comment]
Thank you for all the great work!

**Comment by benjchristensen** [comment]
2.0.0-DP.1 is on its way to Maven Central. I have no idea if this works properly ... this is just a preview release.
