### ISSUE TITLE
Can't find Turbine on Maven central

### ISSUE THREAD

**Issue by lennartkoopmann** [Netflix/Turbine#6]
http://search.maven.org/#search%7Cga%7C1%7Cturbine

What am I missing?

**Comment by pparth** [comment]
+1
Anyone answer please?

**Comment by opuneet** [comment]
Apologies for not getting back to you sooner. I'll work on getting a build of Turbine into maven, meanwhile you can download the source and just build the jar for turbine-core, or build the war for turbine-web which includes turbine-core. 

I'll get back to you soon once I have the artifact in Maven, thanks!

**Comment by opuneet** [comment]
I just released turbine-core and turbine-web artifacts. It can take a few hours to get into Maven. I'll post back when it shows up. Thanks for your patience.

**Comment by pparth** [comment]
Thanks. It's up.

**Comment by opuneet** [comment]
Cool, I'll close this issue.

**Comment by lennartkoopmann** [comment]
Cool, thank you very much! :)
