### ISSUE TITLE
Configuration problem with turbine

### ISSUE THREAD

**Issue by okarahan** [Netflix/Turbine#60]
Hi,
I try to launch Turbine on my local environment, but did not succeeded. I use Spring Boot for my services and my Turbine.

My service which has the @EnableHystrix annotation gives a stream at his hystrix.stream endpoint.

However my Turbine stream is empty. It discovers my service but I didnt know whats going wrong there. Can someone give a simple introduction, I didn't find a good documentation. I only followed these steps here:

http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html

Regards,
Ömer

**Comment by spencergibb** [comment]
@okarahan you should probably post a question like this on http://stackoverflow.com/questions/tagged/spring-cloud or if you have an issue with `spring-cloud-netflix` open an issue [there](https://github.com/spring-cloud/spring-cloud-netflix/issues)

**Comment by okarahan** [comment]
Thank you, sorry for the post here.
