### ISSUE TITLE
Support aggregating events with decimal precision

### ISSUE THREAD

**Issue by mattnelson** [Netflix/Turbine#61]
I want to use turbines aggregation with floating points(double or BigDecimal) rather than whole numbers. I couldn't find anything in the documentation that explicitly stated that only whole numbers are supported.

I have a fork of the 1.x branch that I have working with floating points. I know 1.x is EOL, but is this something that can be considered for 2.x?

**Comment by benjchristensen** [comment]
In practice I have chosen to never attempt floating point math of this type and instead multiply to the decimal precision I want, use whole numbers for all math, then at display time add back the decimals.

**Comment by mattnelson** [comment]
Thanks, we will convert our stream to follow your recommendation.
